const mockCoursesCleaned = [
  {
    id: '4712',
    name: 'Genesee Valley Park',
    isFavorite: false,
    holes: '18',
    city: 'Rochester',
    state: 'NY',
    country: 'United States',
    zip: '14620',
    address: '99 Elmwood Ave.',
    rating: '3.29',
    isPayToPlay: 'No',
    isPrivate: 'No',
  },
  {
    id: '7628',
    name: 'Lookup Park',
    isFavorite: false,
    holes: '9',
    city: 'Henrietta',
    state: 'NY',
    country: 'United States',
    zip: '14467',
    address: '3850 East Henrietta Rd.',
    rating: '3.13',
    isPayToPlay: 'No',
    isPrivate: 'No',
  },
  {
    id: '4937',
    name: 'Monroe Community College DGC',
    isFavorite: false,
    holes: '18',
    city: 'Henrietta',
    state: 'NY',
    country: 'United States',
    zip: '14623',
    address: '',
    rating: '2.94',
    isPayToPlay: 'No',
    isPrivate: 'No',
  },
  {
    id: '6795',
    name: 'Ellison Park',
    isFavorite: false,
    holes: '18',
    city: 'Rochester',
    state: 'NY',
    country: 'United States',
    zip: '14610',
    address: '',
    rating: '3.54',
    isPayToPlay: 'No',
    isPrivate: 'No',
  },
  {
    id: '6443',
    name: 'North Ponds DGC',
    isFavorite: false,
    holes: '9',
    city: 'Webster',
    state: 'NY',
    country: 'United States',
    zip: '14580',
    address: '750 Holt Rd.',
    rating: '1.75',
    isPayToPlay: 'No',
    isPrivate: 'No',
  },
];

export default mockCoursesCleaned;
