const mockCourses = [
  {
    course_id: '4712',
    name: 'Genesee Valley Park',
    holes: '18',
    city: 'Rochester',
    state: 'NY',
    country: 'United States',
    zipcode: '14620',
    latitude: '43.119428',
    longitude: '-77.636679',
    street_addr: '99 Elmwood Ave.',
    reviews: '7',
    rating: '3.29',
    private: '0',
    paytoplay: '0',
    tee_1_clr: 'FF0000',
    tee_2_clr: '',
    tee_3_clr: '',
    tee_4_clr: '',
    dgcr_url: 'http://www.dgcoursereview.com/course.php?id=4712',
    dgcr_mobile_url: 'http://www.dgcoursereview.com/mobile/course.php?id=4712',
    rating_img: 'http://www.dgcoursereview.com/images/rating/discs_3.5.png',
    rating_img_small:
      'http://www.dgcoursereview.com/images/rating/discs_sm_3.5.png',
  },
  {
    course_id: '7628',
    name: 'Lookup Park',
    holes: '9',
    city: 'Henrietta',
    state: 'NY',
    country: 'United States',
    zipcode: '14467',
    latitude: '43.045582',
    longitude: '-77.617742',
    street_addr: '3850 East Henrietta Rd.',
    reviews: '4',
    rating: '3.13',
    private: '0',
    paytoplay: '0',
    tee_1_clr: 'FF0000',
    tee_2_clr: '',
    tee_3_clr: '',
    tee_4_clr: '',
    dgcr_url: 'http://www.dgcoursereview.com/course.php?id=7628',
    dgcr_mobile_url: 'http://www.dgcoursereview.com/mobile/course.php?id=7628',
    rating_img: 'http://www.dgcoursereview.com/images/rating/discs_3.png',
    rating_img_small:
      'http://www.dgcoursereview.com/images/rating/discs_sm_3.png',
  },
  {
    course_id: '4937',
    name: 'Monroe Community College DGC',
    holes: '18',
    city: 'Henrietta',
    state: 'NY',
    country: 'United States',
    zipcode: '14623',
    latitude: '43.103033',
    longitude: '-77.605526',
    street_addr: '',
    reviews: '16',
    rating: '2.94',
    private: '0',
    paytoplay: '0',
    tee_1_clr: 'FFFF00',
    tee_2_clr: '000000',
    tee_3_clr: '',
    tee_4_clr: '',
    dgcr_url: 'http://www.dgcoursereview.com/course.php?id=4937',
    dgcr_mobile_url: 'http://www.dgcoursereview.com/mobile/course.php?id=4937',
    rating_img: 'http://www.dgcoursereview.com/images/rating/discs_3.png',
    rating_img_small:
      'http://www.dgcoursereview.com/images/rating/discs_sm_3.png',
  },
  {
    course_id: '6795',
    name: 'Ellison Park',
    holes: '18',
    city: 'Rochester',
    state: 'NY',
    country: 'United States',
    zipcode: '14610',
    latitude: '43.153154',
    longitude: '-77.527428',
    street_addr: '',
    reviews: '12',
    rating: '3.54',
    private: '0',
    paytoplay: '0',
    tee_1_clr: '',
    tee_2_clr: '',
    tee_3_clr: '0000CC',
    tee_4_clr: '',
    dgcr_url: 'http://www.dgcoursereview.com/course.php?id=6795',
    dgcr_mobile_url: 'http://www.dgcoursereview.com/mobile/course.php?id=6795',
    rating_img: 'http://www.dgcoursereview.com/images/rating/discs_3.5.png',
    rating_img_small:
      'http://www.dgcoursereview.com/images/rating/discs_sm_3.5.png',
  },
  {
    course_id: '6443',
    name: 'North Ponds DGC',
    holes: '9',
    city: 'Webster',
    state: 'NY',
    country: 'United States',
    zipcode: '14580',
    latitude: '43.216217',
    longitude: '-77.439955',
    street_addr: '750 Holt Rd.',
    reviews: '2',
    rating: '1.75',
    private: '0',
    paytoplay: '0',
    tee_1_clr: '',
    tee_2_clr: 'FF9900',
    tee_3_clr: '',
    tee_4_clr: '',
    dgcr_url: 'http://www.dgcoursereview.com/course.php?id=6443',
    dgcr_mobile_url: 'http://www.dgcoursereview.com/mobile/course.php?id=6443',
    rating_img: 'http://www.dgcoursereview.com/images/rating/discs_2.png',
    rating_img_small:
      'http://www.dgcoursereview.com/images/rating/discs_sm_2.png',
  },
];

export default mockCourses;
