[
  {
    "id": "4712",
    "name": "Genesee Valley Park",
    "isFavorite": false,
    "holes": "18",
    "city": "Rochester",
    "state": "NY",
    "country": "United States",
    "zip": "14620",
    "address": "99 Elmwood Ave.",
    "reviews": "7",
    "rating": "3.29",
    "payToPlay": "0"
  },
  {
    "id": "7628",
    "name": "Lookup Park",
    "isFavorite": false,
    "holes": "9",
    "city": "Henrietta",
    "state": "NY",
    "country": "United States",
    "zip": "14467",
    "address": "3850 East Henrietta Rd.",
    "reviews": "4",
    "rating": "3.13",
    "payToPlay": "0"
  },
  {
    "id": "4937",
    "name": "Monroe Community College DGC",
    "isFavorite": false,
    "holes": "18",
    "city": "Henrietta",
    "state": "NY",
    "country": "United States",
    "zip": "14623",
    "address": "",
    "reviews": "16",
    "rating": "2.94",
    "payToPlay": "0"
  },
  {
    "id": "6795",
    "name": "Ellison Park",
    "isFavorite": false,
    "holes": "18",
    "city": "Rochester",
    "state": "NY",
    "country": "United States",
    "zip": "14610",
    "address": "",
    "reviews": "12",
    "rating": "3.54",
    "payToPlay": "0"
  },
  {
    "id": "6443",
    "name": "North Ponds DGC",
    "isFavorite": false,
    "holes": "9",
    "city": "Webster",
    "state": "NY",
    "country": "United States",
    "zip": "14580",
    "address": "750 Holt Rd.",
    "reviews": "2",
    "rating": "1.75",
    "payToPlay": "0"
  }
]